### ISSUE TITLE
Matched text in popup menus is near-invisible

### ISSUE THREAD

**Issue by jacobwalkr** [idleberg/vscode-subway#15]
Text in lists like code completion and the command palette is highlighted when it matches your input but since a recent VS Code update, the matched portion of the text is very similar in colour to the background and so it's nearly invisible. I've been using Zürich but the same appears to be true of all the other light Subway themes.

Here are two examples:

![image](https://user-images.githubusercontent.com/2103207/123404360-e3e74400-d5a0-11eb-8891-52d65d6888f6.png)
![image](https://user-images.githubusercontent.com/2103207/123405747-09c11880-d5a2-11eb-8873-78554ba3bd24.png)

**Comment by idleberg** [comment]
The thing is that VSCode supports TextMate themes out of the box. These themes are [verbatim copies](https://packagecontrol.io/packages/Subway%20Color%20Schemes) and meant for syntax highlighting only. In more recent years, Microsoft has introduced a custom theme format for VSCode which extends to other parts of the UI (including that completion popup). Unfortunately, I'm not aware of an extension (or any other tool) to convert TextMate into VSCode themes.

If there was such a tool, I'd consider converting these themes into this new format. Otherwise, I have little time and interest to do so by hand – sorry!

**Comment by idleberg** [comment]
Turns out that VSCodes built-in conversion command comes pretty close to its own theme format. I might give it a shot!

**Comment by idleberg** [comment]
Fixed in v1.1: I would have preferred a less opinionated approach for parts of the UI, but since there are no means to differentiate highlighted words with and without focus, this appeared to be the best solution.

**Comment by jacobwalkr** [comment]
Amazing, thank you! I looked at the TextMate format file and had no idea where to look. Looking forward to seeing this. Thanks again for all your work - I don't know how you keep up with it but I really wasn't expecting you to get to this so fast 😁
